version: "3.9"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - openvpn_config:/etc/openvpn

  quetzal:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: quetzal
    restart: always
    ports:
      - "8080:8080/tcp"
    volumes:
      - openvpn_config:/etc/openvpn
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/db?user=user
      - POSTGRES_PASSWORD=password
      - DEVELOPMENT=false
      - JWT_SECRET=secret
      - JWT_EXP_SECS=86400
      - ADMIN_PASSWORD=password
      - OPENVPN_HOST=openvpn
      - OPENVPN_PORT=1194
      - OPENVPN_CONFIG_PATH=/etc/openvpn
      - OPENVPN_PKI_PATH=/etc/openvpn/pki
    depends_on:
      - db
      - openvpn

volumes:
    db_data:
      driver: local
      name: db_data
    openvpn_config:
        driver: local
        name: openvpn_config