version: "3.9"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  openvpn:
    cap_add:
      - NET_ADMIN
    build:
        context: .
        dockerfile: openvpn.Dockerfile
    container_name: openvpn
    command: /etc/openvpn-setup/configure.sh
    ports:
      - "11940:11940/tcp"
      - "9999:9999"

    volumes:
      - ./openvpn_data:/etc/openvpn


  quetzal:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: quetzal
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./openvpn_data:/etc/openvpn
      - ./easyrsa:/mnt/easyrsa
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/db?user=user
      - POSTGRES_PASSWORD=password
      - DEVELOPMENT=false
      - JWT_SECRET=secret
      - JWT_EXP_SECS=86400
      - ADMIN_PASSWORD=password
      - OPENVPN_HOST=openvpn
      - OPENVPN_PORT=11940
      - OPENVPN_CONFIG_PATH=/etc/openvpn
      - OPENVPN_EASYRSA_PATH=/usr/share/easy-rsa
      - EASYRSA_PKI=/etc/openvpn/easyrsa/pki
      - OPENVPN_MANAGEMENT_PORT=9999
    depends_on:
      - db
      - openvpn

volumes:
    db_data:
      driver: local
      name: db_data
